# Generated by Django 5.2.3 on 2025-06-14 08:53

import author.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4), author.validators.NamesValidator])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), author.validators.NamesValidator])),
                ('passcode', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('info', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
