# Generated by Django 5.2.3 on 2025-06-14 10:54

import author.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_pets_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4), author.validators.NamesValidator()]),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), author.validators.NamesValidator()]),
        ),
        migrations.AlterField(
            model_name='author',
            name='passcode',
            field=models.CharField(validators=[author.validators.PasscodeLengthValidator()]),
        ),
    ]
