# Generated by Django 5.2.3 on 2025-06-14 10:55

import author.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_author_first_name_alter_author_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='passcode',
            field=models.CharField(max_length=6, validators=[author.validators.PasscodeLengthValidator()]),
        ),
    ]
