# Generated by Django 5.2.3 on 2025-06-22 06:49

import django.core.validators
import organizer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=110, validators=[django.core.validators.MinLengthValidator(2), organizer.validators.CompanyNameValidator()])),
                ('phone_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Enter digits only')])),
                ('secret_key', models.CharField(validators=[organizer.validators.SecretKeyValidator()])),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
