# Generated by Django 5.2.3 on 2025-06-22 10:02

import organizer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='secret_key',
            field=models.CharField(max_length=4, validators=[organizer.validators.SecretKeyValidator()]),
        ),
    ]
